export const rateIndex = [
  { name: "Central Kootenay C", value: 2 },
  { name: "Kootenay 1", value: 3 },
  { name: "Okanagan-Similkameen D", value: 10 },
  { name: "Harrison Hot Springs", value: 6 },
  { name: "Central Kootenay G", value: 5 },
  { name: "Okanagan-Similkameen F", value: 10 },
  { name: "Central Kootenay J", value: 9 },
  { name: "Elkford", value: 3 },
  { name: "Central Kootenay K", value: 10 },
  { name: "Mission", value: 4 },
  { name: "Kootenay Boundary D / Rural Grand Forks", value: 4 },
  { name: "Richmond", value: 2 },
  { name: "East Kootenay E", value: 3 },
  { name: "Schkam 2", value: 3 },
  { name: "Tseatah 2", value: 7 },
  { name: "Isidore's Ranch 4", value: 7 },
  { name: "East Kootenay B", value: 10 },
  { name: "Invermere", value: 5 },
  { name: "Kaslo", value: 2 },
  { name: "Radium Hot Springs", value: 9 },
  { name: "Summerland", value: 10 },
  { name: "Fruitvale", value: 10 },
  { name: "Greenwood", value: 1 },
  { name: "Okanagan-Similkameen C", value: 1 },
  { name: "Keremeos", value: 6 },
  { name: "Fraser Valley B", value: 1 },
  { name: "Creston", value: 8 },
  { name: "Skwahla 2", value: 3 },
  { name: "Aitchelitch 9", value: 10 },
  { name: "Alexis 9", value: 4 },
  { name: "Fernie", value: 4 },
  { name: "Castlegar", value: 5 },
  { name: "Kootenay Boundary E / West Boundary", value: 8 },
  { name: "Penticton", value: 8 },
  { name: "Bucktum 4", value: 8 },
  { name: "Silverton", value: 10 },
  { name: "Coquitlam", value: 2 },
  { name: "Esquimalt", value: 6 },
  { name: "Malachan 11", value: 1 },
  { name: "Okanagan-Similkameen G", value: 9 },
  { name: "Fraser Valley D", value: 8 },
  { name: "Strathcona B", value: 3 },
  { name: "Okanagan-Similkameen A", value: 9 },
  { name: "Skawahlook 1", value: 8 },
  { name: "Boothroyd 13", value: 8 },
  { name: "East Kootenay A", value: 4 },
  { name: "New Westminster", value: 1 },
  { name: "Central Kootenay E", value: 6 },
  { name: "Canal Flats", value: 5 },
  { name: "Columbia Lake 3", value: 9 },
  { name: "Central Kootenay A", value: 2 },
  { name: "Sparwood", value: 8 },
  { name: "Central Kootenay D", value: 5 },
  { name: "Cranbrook", value: 4 },
  { name: "Kootenay Boundary B / Lower Columbia-Old-Glory", value: 9 },
  { name: "West Vancouver", value: 8 },
  { name: "Kimberley", value: 8 },
  { name: "Fraser Valley A", value: 1 },
  { name: "Nakusp", value: 5 },
  { name: "East Kootenay C", value: 3 },
  { name: "Chawathil 4", value: 3 },
  { name: "Central Kootenay B", value: 3 },
  { name: "Boston Bar 1A", value: 8 },
  { name: "Clakamucus 2", value: 10 },
  { name: "Pitt Meadows", value: 7 },
  { name: "Maple Ridge", value: 5 },
  { name: "Nanaimo G", value: 3 },
  { name: "Cassimayooks (Mayook) 5", value: 10 },
  { name: "Midway", value: 4 },
  { name: "Stullawheets 8", value: 7 },
  { name: "Osoyoos", value: 6 },
  { name: "North Saanich", value: 4 },
  { name: "East Kootenay F", value: 2 },
  { name: "Tzeachten 13", value: 3 },
  { name: "Gold River", value: 8 },
  { name: "Salmo", value: 5 },
  { name: "Yale Town 1", value: 1 },
  { name: "Creston 1", value: 9 },
  { name: "Fraser Valley C", value: 3 },
  { name: "Squawkum Creek 3", value: 5 },
  { name: "Skway 5", value: 2 },
  { name: "Nanaimo", value: 9 },
  { name: "Tsawwassen", value: 5 },
  { name: "Cowichan", value: 10 },
  { name: "Tipella 7", value: 8 },
  { name: "Galiano Island 9", value: 1 },
  { name: "Kwawkwawapilt 6", value: 6 },
  { name: "Squiaala", value: 4 },
  { name: "Belcarra", value: 5 },
  { name: "Douglas 8", value: 1 },
  { name: "New Denver", value: 5 },
  { name: "Warfield", value: 6 },
  { name: "Okanagan-Similkameen B", value: 8 },
  { name: "Comox 1", value: 2 },
  { name: "Matsqui Main 2", value: 7 },
  { name: "Powell River A", value: 6 },
  { name: "Coquitlam 2", value: 6 },
  { name: "Tahsis", value: 4 },
  { name: "Est-Patrolas 4", value: 6 },
  { name: "Abbotsford", value: 9 },
  { name: "Lukseetsissum 9", value: 9 },
  { name: "Village Island 1", value: 8 },
  { name: "Ashnola 10", value: 10 },
  { name: "Peters 1", value: 4 },
  { name: "Sooke", value: 1 },
  { name: "Shuswap", value: 6 },
  { name: "Juan de Fuca (Part 2)", value: 3 },
  { name: "Kootenay Boundary A", value: 5 },
  { name: "Princeton", value: 2 },
  { name: "Central Kootenay I", value: 8 },
  { name: "Penticton 1", value: 8 },
  { name: "Popkum 1", value: 5 },
  { name: "Lower Similkameen 2", value: 1 },
  { name: "Slocan", value: 4 },
  { name: "Hope", value: 5 },
  { name: "Portier Pass 5", value: 2 },
  { name: "Fraser Valley F", value: 3 },
  { name: "Ohamil 1", value: 1 },
  { name: "Skwali 3", value: 3 },
  { name: "East Kootenay G", value: 1 },
  { name: "Burrard Inlet 3", value: 7 },
  { name: "Central Kootenay F", value: 1 },
  { name: "Chehalis 5", value: 9 },
  { name: "Fountain  1", value: 9 },
  { name: "Tsahaheh 1", value: 4 },
  { name: "Ahahswinis 1", value: 1 },
  { name: "Sunshine Coast F", value: 6 },
  { name: "Central Kootenay H", value: 6 },
  { name: "Chopaka 7 & 8", value: 2 },
  { name: "Katzie 1", value: 2 },
  { name: "Campbell River", value: 6 },
  { name: "Anacla 12", value: 3 },
  { name: "Trail", value: 7 },
  { name: "Albert Flat 5", value: 2 },
  { name: "Squirrel Cove 8", value: 1 },
  { name: "Montrose", value: 10 },
  { name: "Langley", value: 2 },
  { name: "Ladysmith", value: 9 },
  { name: "Juan de Fuca (Part 1)", value: 7 },
  { name: "Anmore", value: 2 },
  { name: "Vancouver", value: 4 },
  { name: "Courtenay", value: 7 },
  { name: "New Songhees 1A", value: 4 },
  { name: "Nanaimo C", value: 5 },
  { name: "Upper Sumas 6", value: 1 },
  { name: "Chemainus 13", value: 5 },
  { name: "Ittatsoo 1", value: 5 },
  { name: "North Vancouver", value: 9 },
  { name: "Musqueam 2", value: 9 },
  { name: "Paqulh", value: 3 },
  { name: "Fraser Valley H", value: 8 },
  { name: "Grand Forks", value: 5 },
  { name: "Saltspring Island", value: 8 },
  { name: "Kluskus 1", value: 5 },
  { name: "Langford", value: 4 },
  { name: "Fountain 11", value: 1 },
  { name: "Squamish-Lillooet B", value: 9 },
  { name: "Pentledge 2", value: 9 },
  { name: "Nanaimo Town 1", value: 3 },
  { name: "Cheam 1", value: 2 },
  { name: "Burnaby", value: 1 },
  { name: "Paul's Basin 2", value: 8 },
  { name: "Kent", value: 7 },
  { name: "Katzie 2", value: 8 },
  { name: "Nicomen 1", value: 5 },
  { name: "Greater Vancouver A", value: 1 },
  { name: "Esquimalt", value: 9 },
  { name: "Okanagan-Similkameen E", value: 1 },
  { name: "Seabird Island", value: 6 },
  { name: "Fraser Valley G", value: 9 },
  { name: "Blind Creek 6", value: 7 },
  { name: "Q'alatkú7em", value: 7 },
  { name: "Osoyoos 1", value: 3 },
  { name: "Okanagan-Similkameen H", value: 4 },
  { name: "Lakahahmen 11", value: 6 },
  { name: "Numukamis 1", value: 6 },
  { name: "Lake Cowichan", value: 6 },
  { name: "Lions Bay", value: 7 },
  { name: "Scowlitz 1", value: 10 },
  { name: "Tobacco Plains 2", value: 2 },
  { name: "Cowichan Valley C", value: 9 },
  { name: "Soowahlie 14", value: 8 },
  { name: "Coquitlam 1", value: 7 },
  { name: "Chilco Lake 1A", value: 5 },
  { name: "Slosh 1", value: 2 },
  { name: "Sunshine Coast A", value: 9 },
  { name: "Switsemalph 3", value: 1 },
  { name: "Spuzzum 1", value: 6 },
  { name: "Yakweakwioose 12", value: 10 },
  { name: "Alberni-Clayoquot D", value: 3 },
  { name: "Campbell River 11", value: 6 },
  { name: "Strathcona C", value: 3 },
  { name: "Fraser Valley E", value: 9 },
  { name: "Holachten 8", value: 4 },
  { name: "Mission 5", value: 8 },
  { name: "Kootenay Boundary C / Christina Lake", value: 7 },
  { name: "Colwood", value: 1 },
  { name: "Tsussie 6", value: 1 },
  { name: "Cowichan Valley G", value: 3 },
  { name: "Becher Bay 1", value: 1 },
  { name: "Cowichan Valley A", value: 2 },
  { name: "Chuchhraischin", value: 3 },
  { name: "Nanaimo H", value: 3 },
  { name: "Nanaimo River", value: 7 },
  { name: "Shingle Point 4", value: 1 },
  { name: "Comox Valley C (Puntledge - Black Creek)", value: 10 },
  { name: "Lytton", value: 5 },
  { name: "Halalt 2", value: 8 },
  { name: "Stryen 9", value: 6 },
  { name: "Sachteen", value: 4 },
  { name: "Gordon River 2", value: 4 },
  { name: "Puckatholetchin 11", value: 1 },
  { name: "Strathcona A", value: 8 },
  { name: "Louis Squinas Ranch 14", value: 1 },
  { name: "Highlands", value: 4 },
  { name: "Thompson-Nicola E (Bonaparte Plateau)", value: 3 },
  { name: "Seton Lake 5", value: 1 },
  { name: "Skuppah 2A", value: 4 },
  { name: "Sayward", value: 1 },
  { name: "Alberni-Clayoquot F", value: 4 },
  { name: "Musqueam 4", value: 2 },
  { name: "Bella Bella 1", value: 5 },
  { name: "Inkahtsaph 6", value: 2 },
  { name: "Cowichan Valley I", value: 2 },
  { name: "Salmon River Meadow 7", value: 5 },
  { name: "Sidney", value: 9 },
  { name: "Ucluelet", value: 4 },
  { name: "Chuchuwayha 2", value: 8 },
  { name: "Langley", value: 9 },
  { name: "Speyum 3", value: 7 },
  { name: "Tuckkwiowhum 1", value: 9 },
  { name: "White Rock", value: 2 },
  { name: "Whonnock 1", value: 4 },
  { name: "Chilliwack", value: 7 },
  { name: "Surrey", value: 7 },
  { name: "Gibsons", value: 7 },
  { name: "Nanoose", value: 6 },
  { name: "Cowichan Valley F", value: 8 },
  { name: "Port Alberni", value: 3 },
  { name: "Nelson", value: 5 },
  { name: "McCartney's Flat 4", value: 2 },
  { name: "Schelowat 1", value: 2 },
  { name: "Matsqui 4", value: 5 },
  { name: "Tanakut 4", value: 8 },
  { name: "Nekalliston 2", value: 6 },
  { name: "Enderby 2", value: 5 },
  { name: "Trout Lake Alec 16", value: 7 },
  { name: "Sunshine Coast B", value: 1 },
  { name: "Port Coquitlam", value: 1 },
  { name: "Tin Wis 11", value: 4 },
  { name: "Tsa Xana 18", value: 10 },
  { name: "Bridge River 1", value: 2 },
  { name: "Kopchitchin 2", value: 9 },
  { name: "Skowkale", value: 4 },
  { name: "High Bar 1", value: 8 },
  { name: "Oliver", value: 1 },
  { name: "Malahat 11", value: 1 },
  { name: "Sunshine Coast D", value: 6 },
  { name: "Cowichan Valley E", value: 5 },
  { name: "Hesquiat 1", value: 7 },
  { name: "Qualicum Beach", value: 5 },
  { name: "Lytton 4E", value: 8 },
  { name: "Qualicum", value: 2 },
  { name: "Sechelt (Part)", value: 8 },
  { name: "Nanaimo A", value: 8 },
  { name: "Nesuch 3", value: 8 },
  { name: "Nuuautin 2", value: 5 },
  { name: "Macoah 1", value: 3 },
  { name: "Hope Island 1", value: 9 },
  { name: "Port Moody", value: 7 },
  { name: "Fountain  3", value: 1 },
  { name: "McMillan Island 6", value: 8 },
  { name: "Oclucje 7", value: 5 },
  { name: "Ulkatcho 14A", value: 6 },
  { name: "Ahaminaquus 12", value: 9 },
  { name: "Enderby", value: 1 },
  { name: "Ashcroft", value: 2 },
  { name: "Coldstream", value: 6 },
  { name: "Squamish", value: 1 },
  { name: "Merritt", value: 1 },
  { name: "Central Saanich", value: 1 },
  { name: "Kitimat-Stikine F", value: 10 },
  { name: "Semiahmoo", value: 5 },
  { name: "Lantzville", value: 6 },
  { name: "Kitimat-Stikine E", value: 10 },
  { name: "Union Bay 4", value: 1 },
  { name: "Skuppah 4", value: 5 },
  { name: "South Saanich 1", value: 1 },
  { name: "Langley 5", value: 8 },
  { name: "Skookumchuck 4", value: 6 },
  { name: "Duncan", value: 9 },
  { name: "Delta", value: 10 },
  { name: "Oak Bay", value: 3 },
  { name: "Nanaimo E", value: 5 },
  { name: "Oyster Bay 12", value: 5 },
  { name: "One Hundred Mile House", value: 9 },
  { name: "Cariboo I", value: 7 },
  { name: "Klehkoot 2", value: 5 },
  { name: "Alberni-Clayoquot C", value: 2 },
  { name: "Rossland", value: 4 },
  { name: "Zacht 5", value: 4 },
  { name: "Columbia-Shuswap D", value: 10 },
  { name: "West Kelowna", value: 6 },
  { name: "Hagwilget 1", value: 7 },
  { name: "Switsemalph", value: 5 },
  { name: "North Bay 5", value: 2 },
  { name: "Alkali Lake 4A", value: 9 },
  { name: "Douglas Lake 3", value: 2 },
  { name: "Cowichan Valley D", value: 10 },
  { name: "Sechelt (Part)", value: 8 },
  { name: "Spences Bridge", value: 8 },
  { name: "Columbia-Shuswap B", value: 3 },
  { name: "Saddle Rock 9", value: 9 },
  { name: "Penelakut Island 7", value: 9 },
  { name: "Ashcroft 4", value: 5 },
  { name: "Saanich", value: 8 },
  { name: "Chenahkint 12", value: 7 },
  { name: "Chekwelp 26", value: 7 },
  { name: "Lillooet 1", value: 9 },
  { name: "Cayoosh Creek 1", value: 6 },
  { name: "Zeballos", value: 10 },
  { name: "Spallumcheen", value: 4 },
  { name: "Homalco 9", value: 10 },
  { name: "Cache Creek", value: 8 },
  { name: "Powell River E", value: 10 },
  { name: "Thompson-Nicola J (Copper Desert Country)", value: 10 },
  { name: "Shackan 11", value: 10 },
  { name: "Quinsam 12", value: 6 },
  { name: "Central Coast D", value: 5 },
  { name: "Bowen Island", value: 3 },
  { name: "Nooaitch 10", value: 2 },
  { name: "Victoria", value: 10 },
  { name: "Towinock 2", value: 9 },
  { name: "Powell River B", value: 1 },
  { name: "Quaaout 1", value: 5 },
  { name: "Nicola Mameet 1", value: 6 },
  { name: "Gwayasdums 1", value: 7 },
  { name: "Basque 18", value: 6 },
  { name: "Joeyaska 2", value: 4 },
  { name: "T'Sou-ke", value: 6 },
  { name: "Kitimat-Stikine D", value: 4 },
  { name: "Cumberland", value: 9 },
  { name: "Esowista 3", value: 8 },
  { name: "Nak'azdli (Necoslie 1)", value: 9 },
  { name: "Alberni 2", value: 7 },
  { name: "Armstrong", value: 1 },
  { name: "Tzart-Lam 5", value: 1 },
  { name: "Metchosin", value: 4 },
  { name: "North Vancouver", value: 10 },
  { name: "Kil-pah-las 3", value: 8 },
  { name: "Capilano 5", value: 1 },
  { name: "Marktosis 15", value: 8 },
  { name: "Yuquot 1", value: 3 },
  { name: "Houpsitas 6", value: 4 },
  { name: "Kippase 2", value: 8 },
  { name: "Canim Lake 2", value: 10 },
  { name: "Sunshine Coast E", value: 7 },
  { name: "Lillooet", value: 1 },
  { name: "Kahmoose 4", value: 4 },
  { name: "Columbia-Shuswap C", value: 8 },
  { name: "Deep Creek 2", value: 2 },
  { name: "Dog Creek 2", value: 6 },
  { name: "Dzitline Lee 9", value: 7 },
  { name: "Cariboo G", value: 8 },
  { name: "Woyenne 27", value: 6 },
  { name: "Anahim's Meadow", value: 7 },
  { name: "Central Okanagan", value: 9 },
  { name: "Ehatis 11", value: 6 },
  { name: "Nicola Lake 1", value: 6 },
  { name: "Sicamous", value: 9 },
  { name: "Salmon Arm", value: 1 },
  { name: "Skwah 4", value: 4 },
  { name: "Elhlateese 2", value: 4 },
  { name: "Siska Flat", value: 6 },
  { name: "Nanaimo B", value: 10 },
  { name: "Cape Mudge 10", value: 6 },
  { name: "Fountain 1B", value: 4 },
  { name: "Thompson-Nicola N (Beautiful Nicola Valley - South)", value: 8 },
  { name: "Canoe Creek 2", value: 1 },
  { name: "Sechelt", value: 10 },
  { name: "Salmon River 1", value: 10 },
  { name: "Kowtain 17", value: 10 },
  { name: "Kumcheen 1", value: 7 },
  { name: "Fountain 10", value: 1 },
  { name: "Nickel Palm 4", value: 7 },
  { name: "Cariboo A", value: 6 },
  { name: "Inkluckcheen", value: 2 },
  { name: "Kitasoo 1", value: 9 },
  { name: "Southern Gulf Islands", value: 7 },
  { name: "Quesnel", value: 4 },
  { name: "East Saanich 2", value: 9 },
  { name: "Lytton 9A", value: 9 },
  { name: "Halhalaeden", value: 5 },
  { name: "Canoe Creek 3", value: 8 },
  { name: "Columbia-Shuswap E", value: 8 },
  { name: "Bella Coola 1", value: 2 },
  { name: "Oregon Jack Creek 5", value: 3 },
  { name: "Pemynoos 9", value: 4 },
  { name: "Cowichan Valley B", value: 10 },
  { name: "Tacla Lake (Ferry Landing) 9", value: 1 },
  { name: "Nekliptum  1", value: 10 },
  { name: "Comox Valley B (Lazo North)", value: 1 },
  { name: "Seaspunkut 4", value: 7 },
  { name: "Strathcona D (Oyster Bay - Buttle Lake)", value: 7 },
  { name: "Tzetzi Lake 11", value: 2 },
  { name: "Refuge Cove 6", value: 10 },
  { name: "Sachsa 4", value: 6 },
  { name: "Mission 1", value: 5 },
  { name: "Alberni-Clayoquot E", value: 7 },
  { name: "Tofino", value: 6 },
  { name: "Thompson-Nicola I (Blue Sky Country)", value: 4 },
  { name: "Thompson-Nicola L (Grasslands)", value: 8 },
  { name: "Kamloops", value: 5 },
  { name: "Port Edward", value: 5 },
  { name: "Lax Kw'alaams 1", value: 3 },
  { name: "Stawamus 24", value: 5 },
  { name: "Cheakamus 11", value: 5 },
  { name: "Skweahm 10", value: 10 },
  { name: "Scotch Creek 4", value: 9 },
  { name: "Alexis Creek 14", value: 3 },
  { name: "Ye Koo Che 3", value: 2 },
  { name: "Taylor", value: 4 },
  { name: "Agats Meadow 8", value: 1 },
  { name: "Fort Ware 1", value: 3 },
  { name: "Tumbler Ridge", value: 1 },
  { name: "Alert Bay", value: 3 },
  { name: "Powell River C", value: 8 },
  { name: "Quatsino Subdivision 18", value: 8 },
  { name: "Sundayman's Meadow 3", value: 5 },
  { name: "Cariboo B", value: 6 },
  { name: "Barnston Island 3", value: 1 },
  { name: "Nesikep 6", value: 6 },
  { name: "Upper Hat Creek 1", value: 5 },
  { name: "Comox Valley A", value: 7 },
  { name: "Squamish-Lillooet D", value: 3 },
  { name: "Hamilton Creek 2", value: 10 },
  { name: "Canoe Creek 1", value: 5 },
  { name: "Chum Creek 2", value: 3 },
  { name: "Necait 6", value: 5 },
  { name: "Anahim's Flat 1", value: 10 },
  { name: "Fountain Creek 8", value: 7 },
  { name: "Kamloops 1", value: 9 },
  { name: "Skwayaynope 26", value: 1 },
  { name: "Whispering Pines 4", value: 4 },
  { name: "Charley Boy's Meadow 3", value: 7 },
  { name: "North Okanagan D", value: 3 },
  { name: "North Tacla Lake", value: 8 },
  { name: "Chilhil 6", value: 10 },
  { name: "Stone 1", value: 6 },
  { name: "Squaw-hay-one 11", value: 9 },
  { name: "Columbia-Shuswap F", value: 7 },
  { name: "Peq-Paq 22", value: 7 },
  { name: "Port Clements", value: 1 },
  { name: "Ulkatcho 13", value: 2 },
  { name: "Bulkley River 19", value: 3 },
  { name: "Kanaka Bar", value: 5 },
  { name: "Yawaucht 11", value: 7 },
  { name: "Cowichan Lake", value: 6 },
  { name: "Peachland", value: 10 },
  { name: "Pashilqua 2", value: 9 },
  { name: "Peace River D", value: 6 },
  { name: "Tork 7", value: 7 },
  { name: "Queen Charlotte", value: 9 },
  { name: "Fountain 12", value: 3 },
  { name: "Seaichem 16", value: 6 },
  { name: "Seymour Creek 2", value: 2 },
  { name: "Squamish-Lillooet A", value: 7 },
  { name: "Alberni-Clayoquot B", value: 9 },
  { name: "105 Mile Post 2", value: 7 },
  { name: "Thompson-Nicola A (Wells Gray Country)", value: 6 },
  { name: "Sun Peaks Mountain", value: 8 },
  { name: "Prince Rupert", value: 3 },
  { name: "Fraser-Fort George H", value: 4 },
  { name: "Kloklowuck 7", value: 8 },
  { name: "View Royal", value: 6 },
  { name: "Nazco 20", value: 2 },
  { name: "Gitwangak 1", value: 1 },
  { name: "Fraser-Fort George A", value: 8 },
  { name: "Stikine Region", value: 3 },
  { name: "Fishtrap 19", value: 9 },
  { name: "Dease Lake 9", value: 2 },
  { name: "Yekwaupsum 18", value: 7 },
  { name: "Alert Bay", value: 2 },
  { name: "Coryatsaqua (Moricetown) 2", value: 3 },
  { name: "Coglistiko River 29", value: 5 },
  { name: "North Cowichan", value: 2 },
  { name: "Kitzowit 20", value: 3 },
  { name: "Thomas Squinas Ranch 2A", value: 6 },
  { name: "Powell River D", value: 8 },
  { name: "Thompson-Nicola P (Rivers and the Peaks)", value: 9 },
  { name: "Central Okanagan J", value: 8 },
  { name: "Marble Canyon 3", value: 6 },
  { name: "Wells", value: 5 },
  { name: "Clinton", value: 2 },
  { name: "Redstone Flat 1", value: 10 },
  { name: "Kelowna", value: 4 },
  { name: "Lumby", value: 6 },
  { name: "Squaam 2", value: 5 },
  { name: "Williams Lake", value: 10 },
  { name: "Masset", value: 2 },
  { name: "Hustalen 1", value: 4 },
  { name: "Thompson-Nicola B (Thompson Headwaters)", value: 8 },
  { name: "Euchinico Creek 17", value: 7 },
  { name: "Alberni-Clayoquot A", value: 5 },
  { name: "Alexis Creek 34", value: 7 },
  { name: "Paska Island 3", value: 2 },
  { name: "Kitimat-Stikine B", value: 6 },
  { name: "Little Springs", value: 1 },
  { name: "Mackenzie", value: 6 },
  { name: "Cariboo F", value: 10 },
  { name: "Louis Creek 4", value: 3 },
  { name: "Squamish-Lillooet C", value: 6 },
  { name: "Columbia-Shuswap A", value: 2 },
  { name: "Logan Lake", value: 5 },
  { name: "Whistler", value: 5 },
  { name: "Kitimat-Stikine A", value: 6 },
  { name: "Skeetchestn", value: 7 },
  { name: "Zoht 4", value: 6 },
  { name: "Cole Bay 3", value: 9 },
  { name: "Duck Lake 7", value: 5 },
  { name: "Comox", value: 4 },
  { name: "Tsaukan 12", value: 6 },
  { name: "Kleetlekut 22", value: 4 },
  { name: "Barriere", value: 2 },
  { name: "Halfway River 168", value: 6 },
  { name: "Pouce Coupe", value: 3 },
  { name: "Tsulquate 4", value: 5 },
  { name: "Waiwakum 14", value: 7 },
  { name: "Betty Creek 18", value: 8 },
  { name: "Bulkley-Nechako F", value: 5 },
  { name: "S1/2 Tsimpsean 2", value: 4 },
  { name: "Palling 1", value: 5 },
  { name: "Lytton 9B", value: 4 },
  { name: "Babine 17", value: 3 },
  { name: "Sik-e-dakh 2", value: 8 },
  { name: "Kitimat-Stikine C (Part 2)", value: 1 },
  { name: "Parksville", value: 2 },
  { name: "Seah 5", value: 3 },
  { name: "Lezbye  6", value: 9 },
  { name: "Sliammon 1", value: 3 },
  { name: "Cariboo K", value: 9 },
  { name: "Kispiox 1", value: 3 },
  { name: "Williams Lake 1", value: 8 },
  { name: "Nisga'a", value: 3 },
  { name: "Sandy Harry 4", value: 4 },
  { name: "Tsinstikeptum  9", value: 2 },
  { name: "Cariboo J", value: 9 },
  { name: "Shawniken 4B", value: 6 },
  { name: "Quaee 7", value: 9 },
  { name: "Kitsumkaylum 1", value: 4 },
  { name: "Canim Lake 4", value: 1 },
  { name: "Klahkamich 17", value: 6 },
  { name: "Fort Rupert 1", value: 9 },
  { name: "Nequatque", value: 3 },
  { name: "Blackwater Meadow 11", value: 9 },
  { name: "Cariboo H", value: 7 },
  { name: "Telkwa", value: 6 },
  { name: "Tache 1", value: 5 },
  { name: "Nimpkish 2", value: 4 },
  { name: "Boothroyd 8A (Part)", value: 6 },
  { name: "Thompson-Nicola M (Beautiful Nicola Valley - North)", value: 2 },
  { name: "Johny Sticks 2", value: 9 },
  { name: "Lytton 4A", value: 10 },
  { name: "Cariboo C", value: 1 },
  { name: "Iskut 6", value: 2 },
  { name: "Priest's Valley 6", value: 1 },
  { name: "Alexandria", value: 6 },
  { name: "Cowichan Valley H", value: 3 },
  { name: "Golden", value: 10 },
  { name: "Mount Currie", value: 4 },
  { name: "Upper Nepa 6", value: 10 },
  { name: "Klickkumcheen 18", value: 9 },
  { name: "Vernon", value: 2 },
  { name: "Good Hope Lake", value: 9 },
  { name: "Hazelton", value: 6 },
  { name: "Quesnel 1", value: 8 },
  { name: "Skeena-Queen Charlotte C", value: 9 },
  { name: "Dawson Creek", value: 8 },
  { name: "Telegraph Creek", value: 9 },
  { name: "Nohomeen 23", value: 1 },
  { name: "Unnamed 10", value: 7 },
  { name: "Duncan Lake 2", value: 10 },
  { name: "Nanaimo F", value: 8 },
  { name: "North Thompson 1", value: 9 },
  { name: "Port Alice", value: 5 },
  { name: "Pemberton", value: 10 },
  { name: "Lohbiee 3", value: 3 },
  { name: "Gitsegukla 1", value: 2 },
  { name: "Kitimat", value: 8 },
  { name: "Houston", value: 4 },
  { name: "Stellaquo (Stella) 1", value: 4 },
  { name: "Central Coast E", value: 6 },
  { name: "Soda Creek 1", value: 9 },
  { name: "Tsinstikeptum 10", value: 9 },
  { name: "Central Coast A", value: 4 },
  { name: "Laketown 3", value: 3 },
  { name: "North Okanagan E", value: 7 },
  { name: "East Moberly Lake 169", value: 5 },
  { name: "Coldwater 1", value: 8 },
  { name: "Port Hardy", value: 8 },
  { name: "Windy Mouth 7", value: 10 },
  { name: "Omineca 1", value: 1 },
  { name: "Skins Lake 16A", value: 8 },
  { name: "McBride", value: 1 },
  { name: "North Okanagan B", value: 7 },
  { name: "Chase", value: 5 },
  { name: "Michel Gardens 36", value: 2 },
  { name: "Spintlum Flat 3", value: 7 },
  { name: "Alkali Lake 1", value: 1 },
  { name: "Fraser Lake", value: 10 },
  { name: "Alexis Creek 21", value: 5 },
  { name: "New Hazelton", value: 9 },
  { name: "Theik 2", value: 9 },
  { name: "Puntzi Lake 2", value: 3 },
  { name: "Nkaih 10", value: 8 },
  { name: "Sowchea 3", value: 5 },
  { name: "Nickeyeah 25", value: 2 },
  { name: "Towdystan Lake 3", value: 5 },
  { name: "Kitamaat 2", value: 2 },
  { name: "Cahoose 10", value: 4 },
  { name: "Moricetown 1", value: 4 },
  { name: "Cheslatta 1", value: 4 },
  { name: "Baptiste Meadow 2", value: 2 },
  { name: "Tatla West 11", value: 1 },
  { name: "Opitsat 1", value: 5 },
  { name: "Lake Country", value: 10 },
  { name: "Clearwater", value: 7 },
  { name: "Baezaeko River 27", value: 4 },
  { name: "Guhthe Tah 12", value: 5 },
  { name: "Granisle", value: 5 },
  { name: "Uncha Lake 13A", value: 7 },
  { name: "Kahntah 3", value: 5 },
  { name: "Binche 2 (Pinchie 2)", value: 8 },
  { name: "Revelstoke", value: 3 },
  { name: "Skeena-Queen Charlotte A", value: 9 },
  { name: "Okanagan (Part) 1", value: 9 },
  { name: "Inklyuhkinatko 2", value: 8 },
  { name: "Bulkley-Nechako D", value: 7 },
  { name: "Garden", value: 1 },
  { name: "Poison Creek 17A", value: 6 },
  { name: "Williams Prairie Meadow 1A", value: 4 },
  { name: "Peace River E", value: 1 },
  { name: "Cariboo L", value: 7 },
  { name: "Thompson-Nicola O (Lower North Thompson)", value: 9 },
  { name: "Bulkley-Nechako E", value: 7 },
  { name: "North Okanagan C", value: 9 },
  { name: "Cahoose 12", value: 3 },
  { name: "Valemount", value: 6 },
  { name: "Fort George (Shelley) 2", value: 1 },
  { name: "Kshish 4", value: 3 },
  { name: "Harris 3", value: 9 },
  { name: "Mount Waddington D", value: 9 },
  { name: "Alexis Creek 16", value: 4 },
  { name: "Neskonlith", value: 3 },
  { name: "Tatla't East 2", value: 5 },
  { name: "Katit 1", value: 10 },
  { name: "Mount Waddington C", value: 2 },
  { name: "Peace River B", value: 10 },
  { name: "Powell River", value: 6 },
  { name: "Okanagan (Part) 1", value: 9 },
  { name: "Lower Hat Creek 2", value: 8 },
  { name: "Kulkayu (Hartley Bay) 4", value: 2 },
  { name: "Fort Nelson 2", value: 5 },
  { name: "Babine 25", value: 10 },
  { name: "Francois Lake 7", value: 7 },
  { name: "Bulkley-Nechako B", value: 9 },
  { name: "Port McNeill", value: 1 },
  { name: "Kitimat-Stikine C (Part 1)", value: 10 },
  { name: "Hopetown 10A", value: 8 },
  { name: "Fontas 1", value: 9 },
  { name: "Blueberry River 205", value: 8 },
  { name: "Dog Creek 1", value: 7 },
  { name: "North Okanagan F", value: 6 },
  { name: "West Moberly Lake 168A", value: 10 },
  { name: "Nedoats 11", value: 5 },
  { name: "Terrace", value: 5 },
  { name: "Northern Rockies", value: 8 },
  { name: "Burns Lake", value: 8 },
  { name: "Dolphin Island 1", value: 6 },
  { name: "Skeena-Queen Charlotte E", value: 10 },
  { name: "Squinas 2", value: 5 },
  { name: "Canim Lake 1", value: 1 },
  { name: "Fraser-Fort George C", value: 2 },
  { name: "Five Mile Point  3", value: 8 },
  { name: "Thomas Point 5", value: 2 },
  { name: "Pavilion 1", value: 10 },
  { name: "Cariboo D", value: 6 },
  { name: "Mount Waddington A", value: 5 },
  { name: "Hudson's Hope", value: 3 },
  { name: "Chetwynd", value: 3 },
  { name: "Smithers", value: 1 },
  { name: "Central Coast C", value: 1 },
  { name: "Gitanmaax 1", value: 3 },
  { name: "Babine Lake 21B", value: 9 },
  { name: "Skeena-Queen Charlotte D", value: 7 },
  { name: "Cariboo E", value: 9 },
  { name: "Mission Lands 17", value: 4 },
  { name: "Tahltan 1", value: 7 },
  { name: "Fraser-Fort George E", value: 5 },
  { name: "Jean Baptiste 28", value: 10 },
  { name: "Nautley (Fort Fraser) 1", value: 10 },
  { name: "Toosey 1", value: 2 },
  { name: "Fort St. James", value: 9 },
  { name: "Masset 1", value: 4 },
  { name: "Bonaparte 3", value: 6 },
  { name: "Mount Waddington B", value: 7 },
  { name: "Dead Point 5", value: 3 },
  { name: "Fort St. John", value: 7 },
  { name: "Burns Lake 18", value: 3 },
  { name: "Bulkley-Nechako C", value: 5 },
  { name: "Gitanyow 1", value: 10 },
  { name: "Chilco Lake 1", value: 6 },
  { name: "Fraser-Fort George F", value: 7 },
  { name: "Liard River 3", value: 10 },
  { name: "Tadinlay 15", value: 8 },
  { name: "Kulspai 6", value: 4 },
  { name: "Stewart", value: 7 },
  { name: "Papyum 27", value: 10 },
  { name: "Kitselas 1", value: 7 },
  { name: "Babine  6", value: 9 },
  { name: "Lower Post", value: 10 },
  { name: "McLeod Lake 1", value: 7 },
  { name: "Bulkley-Nechako A", value: 1 },
  { name: "Swan Lake  3", value: 4 },
  { name: "Prophet River 4", value: 3 },
  { name: "Vanderhoof", value: 8 },
  { name: "Skins Lake 16B", value: 5 },
  { name: "Sahhaltkum 4", value: 2 },
  { name: "Bulkley-Nechako G", value: 8 },
  { name: "Peace River C", value: 4 },
  { name: "Fraser-Fort George G", value: 6 },
  { name: "Stony Creek 1", value: 3 },
  { name: "Prince George", value: 8 },
  { name: "Fraser-Fort George D", value: 4 },
  { name: "Skidegate 1", value: 6 },
  { name: "Ingenika Point", value: 3 },
  { name: "Doig River 206", value: 3 },
];